language: python
python:
- '3.4'
sudo: false
install:
- pip install -e git+https://github.com/deconst/preparer-sphinx.git#egg=deconstrst
script:
- script/cibuild
env:
  global:
  - secure: Dg8Y/6qhdJ7/nkpYyKqyIxx7EGRIFLWKGS0zZqkXuUwCrojdc8wOek/03ryvcQu8jybT4Ssqxdp3IJTZhE+zsK+6RFl9RTcfH3MIgqd98jlZV8TqdIF61ZaK+taksdTEMsEhrdQNG+UzyyWAzoKkPjBVLcSF1MhGy6RHenmiXGQ=
  - secure: ehtdmqulnSDhIeMRkbPwFm3V9DeYZ7hVy0LHvHHgstmyAV6faRcNZxjAvuCFm78yfreHF2phrSp4Afs3tn3lCIR/uIHzbLLc0slVtvCGHaQFnVuZbykhuEjQfqXZXokFUYs9fo/yuXtp9UsrFJPY2fs62cy9C5b7IRCkTN3f0HU=
  - secure: AgB83vnx8TgX1TZih2i48S81z69OcLERwL4HJJ2vRgfCQ8vvzBrez1mWF6lmeeZ+UL1bMto0/QzZrbKxmQIWYpiC4MVqbmvmYt+acbDIHGvun/lYyDqb05D4Tkwk0sITkv2w3UzWyaLMk1XAl0b7xs8WNK1vx5ma/al+sVOdp7E=
notifications:
  slack:
    secure: VUTDK1CUOl0aCgpii2pb/hnm4kmw7G20BDi3CdL6roXxBa0RFacDxUpu4saKVHiG2bv1ktaIFsFXzvEOpSEObfnISY1wNWUphxc9ElWPb+OErH0m4nbsu9iKKhI7K9ccDUqbLZq0xeNWkWXZVroI0V1ogjYzbkPRSVh1yuv77To=
