src/wadl/networks.wadl:
    title: Rackspace Cloud Networks Developer Guide - API v2.0
    output_directory: rst/devguide/api-operations/networks

src/wadl/ports.wadl:
    title: Rackspace Cloud Networks Developer Guide - API v2.0
    output_directory: rst/devguide/api-operations/ports

src/wadl/subnets.wadl:
    title: Rackspace Cloud Networks Developer Guide - API v2.0
    output_directory: rst/devguide/api-operations/subnets

src/wadl/security-groups.wadl:
    title: Rackspace Cloud Networks Developer Guide - API v2.0
    output_directory: rst/devguide/api-operations/security-groups
